package UrlSimilarity;

public class tagBank {
    
    public tagBank(){
        
    }
    
public String[] getTags(){
    String[] tags ={"Mario","Halo", "Call of Duty", "Super Smash Bros", "Medal Of Honor","Gran Turismo", "Final Fantasy VII", 
       "Kinect Adventures!",	
"Grand Theft Auto V",
"Tetris",	
"Pokémon Red and Blue",	
"Pokémon Red", 
"Pokémon Blue",
"Pokémon Gold and Silver",
"Pokémon Gold",
"Pokémon Silver", 
"Super Mario Land",	
"Super Mario Land 2: 6 Golden Coins",	
"Pokémon Yellow",	
"The Legend of Zelda: Link's Awakening",
"Kirby's Dream Land",	
"The Legend of Zelda: Oracle of Ages",	
"The Legend of Zelda: Oracle of Seasons",	
"Pokémon Crystal",
"Pokémon Trading Card Game",	
"Super Mario Bros. Deluxe",	
"Yu-Gi-Oh Duel Monsters 4: Battle of the Powerful Duelists",	
"Dragon Warrior Monsters",	
"Kirby's Dream Land 2",	
"Dr. Mario",	
"Yu-Gi-Oh! Duel Monsters",	
"Dragon Warrior Monsters 2",	
"Wario Land: Super Mario Land 3",	
"Tamagotchi",	
"Tamagotchi 2",	
"Yu-Gi-Oh! Duel Monsters II: Dark Duel Stories",	
"DuckTales",	
"Yakuman",	
"Pokémon Pinball",
"Kirby's Pinball",	
"The Final Fantasy Legend",	
"Mahjong",	
"Donkey Kong Country",	
"Yu-Gi-Oh! Duel Monsters III: Tri-Holygod Advent",	
"Super Smash Bros. Melee",
"Mario Kart: Double Dash‼",	
"Super Mario Sunshine",	
"The Legend of Zelda: The Wind Waker",	
"Luigi's Mansion",	
"Animal Crossing",	
"Metroid Prime",	
"Sonic Adventure 2 Battle",	
"Pokémon Colosseum",	
"Mario Party 4",	 
"Paper Mario: The Thousand-Year Door",	
"Mario Party 5",	
"Sonic Mega Collection",	
"Star Wars Rogue Squadron II: Rogue Leader",	
"Star Fox Adventures",	
"Mario Party 7",
"Resident Evil 4",
"Mario Party 6",
"Pikmin",	
"Kirby Air Ride",	
"Super Mario Strikers",	
"The Legend of Zelda: Twilight Princess",	
"Mario Golf: Toadstool Tour",	
"Super Monkey Ball 2",	
"Soulcalibur II",	
"Sonic Heroes",	
"Super Monkey Ball",	
"Resident Evil",	
"Lego Star Wars: The Video Game",	
"Final Fantasy Crystal Chronicles",	
"Donkey Kong Jungle Beat",
"Metroid Prime 2: Echoes",	
"Resident Evil Zero",	
"Sonic Adventure DX: Director's Cut",	
"Pokémon XD: Gale of Darkness",	
"Mario Power Tennis",	
"Need for Speed: Underground",	
"Pikmin 2",	
"Spider-Man",	
"Donkey Konga",	
"Need for Speed: Underground 2",	
"Star Fox: Assault",	
"Naruto: Clash of Ninja 2",	
"Shrek 2",	
"Halo 3",	
"Minecraft",
"Call of Duty: Black Ops",
"Halo 4",	
"Call of Duty: Modern Warfare 2",
"Gears of War 2",
"Batman: Arkham City",	
"Grand Theft Auto IV",	
"Call of Duty 4: Modern Warfare",	
"Fable II",	
"Call of Duty: World at War",	
"Gears of War 3",	
"Halo 3: ODST",	
"Kinect Sports",	
"Battlefield 3",
"Forza Motorsport 2",	
"Assassin's Creed",	
"Dance Central",	
"Marvel: Ultimate Alliance",	
"Uno",	
"Dead Rising",	
"Forza Motorsport 3",	
"Guitar Hero II",	
"Saints Row",	
"Assassin's Creed II",	
"The Elder Scrolls IV: Oblivion",	
"Madden NFL 09",	
"Red Dead Redemption",	
"Rock Band",	
"Madden NFL 07",	
"Guitar Hero III: Legends of Rock",	
"Mass Effect 2",	
"Mass Effect",	
"Tom Clancy's Rainbow Six: Vegas",	
"Call of Duty 3",	
"Fallout 3",	
"Madden NFL 08",	
"BioShock",	
"Crackdown",	
"Lost Planet: Extreme Condition",	
"Perfect Dark Zero",	
"Resident Evil 5",
"Tom Clancy's Ghost Recon Advanced Warfighter",	
"Call of Duty 2",	
"Fight Night Round 3",	
"Trials HD",
"UFC 2009 Undisputed",
"Guitar Hero World Tour",	
"Star Wars: The Force Unleashed",	
"Battlefield: Bad Company 2",	
"Rock Band 2",	
"Dead or Alive 4",	
"Halo Wars",	
"Left 4 Dead",	
"Ninja Gaiden II",	
"The Orange Box",	
"Tom Clancy's Ghost Recon Advanced Warfighter 2",	
"Viva Piñata",
"Gran Turismo 2",
"Final Fantasy VIII", 
"Crash Bandicoot 3: Warped",
"Crash Bandicoot", 
"Metal Gear Solid", 
"Final Fantasy IX",
"Tomb Raider II",
"Crash Bandicoot 2: Cortex Strikes Back", 
"Tomb Raider: The Last Revelation", 
"Resident Evil 2",
"Spyro the Dragon", 
"Tekken 3", 
"Tomb Raider", 
"Dragon Warrior VII", 
"Rayman",
"Tomb Raider III", 
"Resident Evil 3: Nemesis", 
"Spyro 2: Ripto's Rage!", 
"Frogger", 
"Tekken 2", 
"Tony Hawk's Pro Skater", 
"Spyro: Year of the Dragon", 
"Driver", 
"Tony Hawk's Pro Skater 2", 
"PaRappa the Rapper", 
"Croc: Legend of the Gobbos", 
"Harry Potter and the Philosopher's Stone",
"Driver 2", 
"Resident Evil",
"Dino Crisis", 
"Final Fantasy Tactics", 
"Namco Museum Volume 3", 
"Crash Team Racing",
"Tony Hawk's Pro Skater 3",
"WWF War Zone", 
"Everybody's Golf", 
"Mortal Kombat Trilogy", 
"Derby Stallion", 
"Silent Hill", 
"WWF SmackDown!", 
"Crash Bash", 
"WWF SmackDown! 2: Know Your Role", 
"Spider-Man", 
"Parasite Eve", 
"Tetris Plus", 
"Syphon Filter", 
"Twisted Metal 2",
"Tomorrow Never Dies",
"Need For Speed III", 
"Yu-Gi-Oh! Forbidden Memories", 
"Namco Museum Volume 1",
"Medal of Honor", 
"A Bug's Life",
"Legacy of Kain: Soul Reaver",
"Madden NFL 99", 
"Tomb Raider Chronicles", 
"Madden NFL 2000", 
"NFL GameDay '98", 
"Rugrats: Search for Reptar", 
"Grand Theft Auto 2", 
"Everybody's Golf 2", 
"Cool Boarders 3", 
"Syphon Filter 2", 
"Need For Speed: High Stakes", 
"Jet Moto 2", 
"WCW Nitro", 
"Twisted Metal III", 
"Dance Dance Revolution", 
"Jet Moto", 
"Spec Ops: Stealth Patrol", 
"Chrono Cross", };
    return tags;
}
public String[] getURLs(){
    String[] urls = { "https://en.wikipedia.org/wiki/List_of_Nintendo_64_games", "https://en.wikipedia.org/wiki/List_of_Nintendo_GameCube_games","https://en.wikipedia.org/wiki/List_of_Wii_games","https://en.wikipedia.org/wiki/List_of_Wii_U_software#Games","https://en.wikipedia.org/wiki/List_of_PlayStation_games","https://en.wikipedia.org/wiki/List_of_PlayStation_2_games","https://en.wikipedia.org/wiki/List_of_PlayStation_3_games_released_on_disc","https://en.wikipedia.org/wiki/List_of_Xbox_games","https://en.wikipedia.org/wiki/List_of_Xbox_360_games", "https://en.wikipedia.org/wiki/List_of_Super_Nintendo_Entertainment_System_games","https://en.wikipedia.org/wiki/List_of_Sega_Genesis_games","https://en.wikipedia.org/wiki/List_of_Nintendo_Entertainment_System_games","https://en.wikipedia.org/wiki/List_of_Game_Boy_games","https://en.wikipedia.org/wiki/List_of_Game_Boy_Color_games","https://en.wikipedia.org/wiki/List_of_Game_Boy_Advance_games","https://en.wikipedia.org/wiki/List_of_Nintendo_DS_games","https://en.wikipedia.org/wiki/List_of_Nintendo_3DS_games","https://en.wikipedia.org/wiki/List_of_PlayStation_Portable_games","https://en.wikipedia.org/wiki/List_of_PlayStation_Vita_games_(A%E2%80%93L)","https://en.wikipedia.org/wiki/List_of_Commodore_64_games_(A%E2%80%93M)","https://en.wikipedia.org/wiki/List_of_Commodore_64_games_(N%E2%80%93Z)"};
    return urls;
}
}